[package]
name = "disk_space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.29.10"

[dev-dependencies]
assert_cmd = "2.0.11"
escargot = "0.5.7"
lazy_static = "1.4.0"

